### ISSUE TITLE
SSR Setup?

### ISSUE THREAD

**Issue by talentlessguy** [godfreyzubiaga/parcel-react-boilerplate#1]
This is a very cool boilerplate but SSR script, e.g. `npx generate-react-parcel-app --ssr=true` would be cool. Parcel has -t flag which can be used for nodejs. I think it will look kinda this:

```bash
$ npx generate-react-parcel-app --ssr=true myApp
$ cd myApp
$ npm run server
> parcel watch server/index.js -d dist/server -t node
> node dist/server/index.js
> parcel public/index.html

Compiled successfully with 121ms
```
And then server starts.
Would be great if server will be written using builtins or Express or Koa2. Of course, it is optional and boilerplate is already very awesome.

**Comment by tomByrer** [comment]
IMHO if SSR is important, would be better just to use [GatsbyJS](https://www.gatsbyjs.org/).
Rock-solid SSR, fairly fast builds thanks the [WebPack5's parred building](https://github.com/gatsbyjs/gatsby/issues/3220), solid ecosystem (many starters, they have full time staff, etc...).

It would not be bad to have SSR here, but it is nice to have a more stripped-down boilerplate.

**Comment by talentlessguy** [comment]
@tomByrer ok, thanks for info
